import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function resetAllTables() {
  await prisma.formSubmission.deleteMany();
  await prisma.form.deleteMany();
  await prisma.contactMessage.deleteMany();
  await prisma.activityLog.deleteMany();
  await prisma.mediaFile.deleteMany();
  await prisma.eventItem.deleteMany();
  await prisma.promoItem.deleteMany();
  await prisma.galleryItem.deleteMany();
  await prisma.brandPartner.deleteMany();
  await prisma.heroSlide.deleteMany();
  await prisma.heroSlideGroup.deleteMany();
  await prisma.siteSetting.deleteMany();
  await prisma.adminUser.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.blogCategory.deleteMany();
  await prisma.product.deleteMany();
  await prisma.productCategory.deleteMany();
}

export async function seedAllTables() {
  console.log("[SEED] Resetting all tables...");
  await resetAllTables();

  console.log("[SEED] Creating product categories...");
  const productCategories = await Promise.all([
    prisma.productCategory.create({ data: { slug: "beauty-health", title: "Beauty & Health", icon: "/assets/img/icon/service_1_1.svg", description: "Membantu menjaga kecantikan kulit, rambut, dan kuku dari dalam, serta mendukung kesehatan tubuh secara menyeluruh. Cocok untuk Anda yang ingin tampil sehat dan percaya diri setiap hari.", sortOrder: 1 } }),
    prisma.productCategory.create({ data: { slug: "mom-kids", title: "Mom & Kids", icon: "/assets/img/icon/service_1_2.svg", description: "Formula khusus untuk kebutuhan ibu dan anak, membantu pertumbuhan optimal, menjaga daya tahan tubuh, serta mendukung kesehatan selama masa kehamilan, menyusui, dan tumbuh kembang si kecil.", sortOrder: 2 } }),
    prisma.productCategory.create({ data: { slug: "multivitamin", title: "Multivitamin", icon: "/assets/img/icon/service_1_3.svg", description: "Suplemen multivitamin lengkap untuk memenuhi kebutuhan harian vitamin dan mineral, menjaga stamina, meningkatkan energi, serta mendukung daya tahan tubuh sepanjang hari.", sortOrder: 3 } }),
    prisma.productCategory.create({ data: { slug: "vitamin-mineral", title: "Vitamin & Mineral", icon: "/assets/img/icon/service_1_4.svg", description: "Lengkapi kebutuhan vitamin dan mineral penting untuk menjaga kesehatan tulang, gigi, otot, serta fungsi tubuh lainnya. Ideal untuk menunjang aktivitas harian yang padat.", sortOrder: 4 } }),
    prisma.productCategory.create({ data: { slug: "kesehatan-jantung", title: "Kesehatan Jantung", icon: "/assets/img/icon/service_1_5.svg", description: "Suplemen dengan kandungan khusus seperti Omega-3 untuk membantu menjaga kesehatan jantung, menurunkan kolesterol, serta mendukung peredaran darah yang lancar.", sortOrder: 5 } }),
    prisma.productCategory.create({ data: { slug: "kesehatan-kulit", title: "Kesehatan Kulit", icon: "/assets/img/icon/service_1_6.svg", description: "Diformulasikan untuk membantu mencerahkan, melembapkan, dan melindungi kulit dari radikal bebas, sehingga kulit tetap sehat, halus, dan tampak awet muda serta mencegah tanda-tanda penuaan dini.", sortOrder: 6 } }),
    prisma.productCategory.create({ data: { slug: "kesehatan-sendi", title: "Kesehatan Sendi", icon: "/assets/img/icon/service_1_7.svg", description: "Membantu menjaga kelenturan dan kekuatan sendi, mengurangi nyeri sendi, serta menunjang aktivitas harian tanpa hambatan. Dengan kandungan nutrisi penting untuk kesehatan persendian.", sortOrder: 7 } }),
    prisma.productCategory.create({ data: { slug: "vitamin-kolesterol", title: "Vitamin Kolesterol", icon: "/assets/img/icon/service_1_8.svg", description: "Membantu menurunkan kadar kolesterol dan trigliserida dalam darah secara alami, serta menjaga kesehatan pembuluh darah dan jantung, dan nutrisi penting yang mendukung metabolisme lemak.", sortOrder: 8 } }),
  ]);
  const catMap = Object.fromEntries(productCategories.map((c) => [c.slug, c.id]));

  console.log("[SEED] Creating products...");
  const ci = ["/assets/img/product/single-image-1.jpg", "/assets/img/product/single-image-2.jpg", "/assets/img/product/single-image-3.jpg"];
  const cf = ["DHA 200mg untuk perkembangan otak janin", "Dilengkapi asam folat dan zat besi", "Aman untuk ibu hamil & menyusui", "Telah bersertifikat BPOM & Halal"];
  const cd = "<p>DHA berkualitas tinggi dari minyak ikan untuk mendukung perkembangan otak, mata, dan sistem saraf janin. Aman untuk ibu hamil dan menyusui.</p>";
  const cs = "Sea-Quill Prenatal DHA diformulasikan untuk ibu hamil dan menyusui, mendukung perkembangan otak dan mata janin.";
  const cc = "DHA 200mg, EPA 100mg, Folic Acid, Iron, Calcium.";
  const cdos = "1 kapsul per hari setelah makan.";
  const ct = ["kehamilan", "dha", "ibu hamil"];
  await prisma.product.createMany({ data: [
    { name: "Sea-Quill Bioster C", slug: "sea-quill-bioster-c", image: "/uploads/1774113064903-4d5228f82b95746e.jpg", images: ci, shortDescription: "Sea-Quill Omega 3 Salmon adalah suplemen minyak ikan premium yang mengandung asam lemak Omega-3 EPA & DHA murni dari salmon Norwegia. Membantu menjaga kesehatan jantung, fungsi otak, serta mendukung daya tahan tubuh setiap hari.", description: "<p>Suplemen ini mengandung minyak ikan salmon alami yang kaya Omega-3 (EPA &amp; DHA) untuk mendukung kesehatan jantung, otak, mata, dan persendian. Diproses dengan teknologi modern sehingga kualitas dan kemurniannya terjaga.</p>", composition: "Salmon Oil, Gelatin, Glycerin, Water, Vitamin E.", dosage: "1-2 kapsul per hari setelah makan atau sesuai anjuran dokter.", sku: "SQ-OM3-60", tags: ["kesehatan jantung", "otak", "salmon oil"], stock: true, rating: 5, reviewCount: 12, features: ["Sumber Omega-3 berkualitas tinggi dari salmon Norwegia", "Membantu menurunkan kolesterol & trigliserida", "Mendukung fungsi otak dan kesehatan mata", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 1, categoryId: catMap["kesehatan-jantung"] },
    { name: "Sea-Quill C 1000 with Rose Hips", slug: "sea-quill-c-1000-with-rose-hips", image: "/uploads/1774112662418-41305796209de4e0.jpg", images: ci, shortDescription: "Sea-Quill Calcium membantu menjaga kepadatan tulang dan gigi, serta mendukung fungsi otot dan saraf. Ideal untuk semua usia, terutama wanita dan lansia.", description: "<p>Suplemen kalsium berkualitas tinggi untuk mendukung kesehatan tulang, gigi, dan fungsi otot. Dilengkapi dengan Vitamin D3 untuk penyerapan kalsium yang optimal.</p>", composition: "Calcium Carbonate, Vitamin D3, Magnesium, Zinc.", dosage: "1 tablet per hari setelah makan.", sku: "SQ-CAL-60", tags: ["tulang", "kalsium", "vitamin d"], stock: true, rating: 5, reviewCount: 8, features: ["Kalsium berkualitas tinggi untuk kepadatan tulang", "Dilengkapi Vitamin D3 untuk penyerapan optimal", "Cocok untuk semua usia", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 2, categoryId: catMap["vitamin-mineral"] },
    { name: "Seaquill PureWay C Extravit", slug: "seaquill-pureway-c-extravit", image: "/uploads/1774112689312-25a575a066ccca22.jpg", images: ci, shortDescription: "Sea-Quill Vitamin C 1000mg dengan formula high-potency untuk meningkatkan daya tahan tubuh, membantu produksi kolagen, dan melindungi sel dari radikal bebas.", description: "<p>Vitamin C dosis tinggi 1000mg dalam bentuk tablet yang mudah dikonsumsi. Membantu meningkatkan imunitas, mempercepat pemulihan, dan menjaga kesehatan kulit.</p>", composition: "Ascorbic Acid 1000mg, Citrus Bioflavonoids, Rose Hips.", dosage: "1 tablet per hari setelah makan.", sku: "SQ-VC-1000", tags: ["imunitas", "vitamin c", "antioksidan"], stock: true, rating: 5, reviewCount: 15, features: ["Vitamin C dosis tinggi 1000mg", "Meningkatkan daya tahan tubuh", "Membantu produksi kolagen untuk kulit sehat", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 3, categoryId: catMap["multivitamin"] },
    { name: "Sea-Quill CalMagZinc Complex", slug: "sea-quill-calmagzinc-complex", image: "/uploads/1774156547835-059515c6b20b361f.jpg", images: ci, shortDescription: "Sea-Quill Biotin mendukung kesehatan rambut, kulit, dan kuku dari dalam. Dengan formula premium untuk kecantikan alami Anda.", description: "<p>Biotin (Vitamin B7) adalah nutrisi penting untuk menjaga kesehatan rambut, kulit, dan kuku. Membantu metabolisme energi dan mendukung pertumbuhan sel.</p>", composition: "Biotin 5000mcg, Vitamin E, Zinc.", dosage: "1 kapsul per hari.", sku: "SQ-BIO-60", tags: ["kecantikan", "rambut", "kulit", "kuku"], stock: true, rating: 4.8, reviewCount: 6, features: ["Biotin 5000mcg untuk rambut dan kuku kuat", "Mendukung kesehatan kulit dari dalam", "Formula premium untuk kecantikan alami", "Telah bersertifikat BPOM & Halal"], isBestSeller: false, isNew: true, status: "published", sortOrder: 4, categoryId: catMap["beauty-health"] },
    { name: "Sea-Quill Herbal Cordyceps", slug: "sea-quill-herbal-cordyceps", image: "/uploads/1774156567011-902cdf5d804f2b7d.jpg", images: ci, shortDescription: "Sea-Quill Kids Multivitamin diformulasikan khusus untuk anak-anak, mendukung tumbuh kembang optimal dan menjaga daya tahan tubuh si kecil.", description: "<p>Multivitamin lengkap untuk anak-anak dengan rasa buah yang disukai. Mengandung vitamin A, C, D, E, dan mineral penting untuk pertumbuhan.</p>", composition: "Vitamin A, C, D3, E, B Complex, Zinc, Iron, Calcium.", dosage: "1 tablet kunyah per hari.", sku: "SQ-KID-60", tags: ["anak", "multivitamin", "tumbuh kembang"], stock: true, rating: 5, reviewCount: 10, features: ["Formula lengkap untuk tumbuh kembang anak", "Rasa buah yang disukai anak-anak", "Mengandung vitamin dan mineral essential", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 5, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal DermaNeem", slug: "sea-quill-herbal-dermaneem", image: "/uploads/1774156589293-1273ecae9be7d05a.jpg", images: ci, shortDescription: "Sea-Quill Glucosamine membantu menjaga kesehatan sendi dan tulang rawan, mengurangi nyeri sendi, serta menunjang mobilitas harian.", description: "<p>Glucosamine Sulfate 1500mg untuk membantu regenerasi tulang rawan dan melindungi persendian. Cocok untuk usia 40+ dan mereka yang aktif berolahraga.</p>", composition: "Glucosamine Sulfate 1500mg, Chondroitin Sulfate, MSM.", dosage: "1 tablet per hari setelah makan.", sku: "SQ-GLU-60", tags: ["sendi", "tulang rawan", "glucosamine"], stock: true, rating: 4.9, reviewCount: 7, features: ["Glucosamine 1500mg untuk kesehatan sendi", "Chondroitin & MSM untuk perlindungan tulang rawan", "Mengurangi nyeri dan kekakuan sendi", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 6, categoryId: catMap["kesehatan-sendi"] },
    { name: "Sea-Quill Herbal Eimunnia", slug: "sea-quill-herbal-eimunnia", image: "/uploads/1774156624667-d104471355bb611d.jpg", images: ci, shortDescription: "Sea-Quill Collagen membantu menjaga elastisitas dan kelembapan kulit, mengurangi kerutan, serta mendukung kesehatan sendi dan tulang.", description: "<p>Marine Collagen Peptides dari ikan laut dalam untuk penyerapan optimal. Membantu regenerasi kulit dan menjaga kekenyalan alami.</p>", composition: "Marine Collagen Peptides, Vitamin C, Hyaluronic Acid.", dosage: "1-2 kapsul per hari.", sku: "SQ-COL-60", tags: ["kulit", "anti aging", "collagen"], stock: true, rating: 4.9, reviewCount: 11, features: ["Marine Collagen dari ikan laut dalam", "Menjaga elastisitas dan kelembapan kulit", "Dilengkapi Vitamin C & Hyaluronic Acid", "Telah bersertifikat BPOM & Halal"], isBestSeller: true, isNew: false, status: "published", sortOrder: 7, categoryId: catMap["kesehatan-kulit"] },
    { name: "Sea-Quill Natural Gamat Sea Cucumber Extract", slug: "sea-quill-natural-gamat-sea-cucumber-extract", image: "/uploads/1774156646516-0852944e7d7b3a5e.jpg", images: ci, shortDescription: "Sea-Quill Red Yeast Rice membantu menurunkan kadar kolesterol secara alami dan menjaga kesehatan kardiovaskular.", description: "<p>Red Yeast Rice (Angkak) mengandung Monacolin K alami yang membantu menghambat produksi kolesterol berlebih di hati. Alternatif alami untuk menjaga kadar kolesterol.</p>", composition: "Red Yeast Rice Extract, Coenzyme Q10, Vitamin E.", dosage: "1 kapsul per hari setelah makan malam.", sku: "SQ-RYR-60", tags: ["kolesterol", "jantung", "red yeast rice"], stock: true, rating: 4.7, reviewCount: 5, features: ["Monacolin K alami untuk menurunkan kolesterol", "Dilengkapi CoQ10 untuk kesehatan jantung", "Alternatif alami tanpa efek samping statin", "Telah bersertifikat BPOM & Halal"], isBestSeller: false, isNew: true, status: "published", sortOrder: 8, categoryId: catMap["vitamin-kolesterol"] },
    { name: "Sea-Quill Herbal Chlorella Freshter", slug: "sea-quill-herbal-chlorella-freshter", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 9, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Ginkgo Spicur", slug: "sea-quill-herbal-ginkgo-spicur", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Hair More", slug: "sea-quill-hair-more", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Mantix", slug: "sea-quill-herbal-mantix", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Spirulina Freshter", slug: "sea-quill-herbal-spirulina-freshter", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Valerian Ext", slug: "sea-quill-herbal-valerian-ext", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Natural Albufish", slug: "sea-quill-natural-albufish", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Obesigone", slug: "sea-quill-herbal-obesigone", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Prostaherbs", slug: "sea-quill-prostaherbs", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Coral CalMagZinc", slug: "sea-quill-coral-calmagzinc", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Omega", slug: "sea-quill-omega", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Black Seed Oil Habbatussauda", slug: "sea-quill-black-seed-oil-habbatussauda", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Jointricare", slug: "sea-quill-jointricare", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill B Complus", slug: "sea-quill-b-complus", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Fish-O-Vit Junior", slug: "sea-quill-fish-o-vit-junior", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Garlicol 800", slug: "sea-quill-garlicol-800", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Omega 369", slug: "sea-quill-omega-369", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Omega HiCons", slug: "sea-quill-omega-hicons", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Selenium ACE", slug: "sea-quill-selenium-ace", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Omega Squaplex", slug: "sea-quill-omega-squaplex", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Sunvit D3 1000 IU", slug: "sea-quill-sunvit-d3-1000-iu", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "draft", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Sunvit D3 + K2", slug: "sea-quill-sunvit-d3-k2", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "draft", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill CollaJuve Skin", slug: "sea-quill-collajuve-skin", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Herbal Sugar Shed", slug: "sea-quill-herbal-sugar-shed", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Motherhood With DHA", slug: "sea-quill-motherhood-with-dha", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Salmon Omega 3", slug: "sea-quill-salmon-omega-3", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Vitamin E 400 IU", slug: "sea-quill-vitamin-e-400-iu", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill Calendula  Soothing Gel", slug: "sea-quill-calendula-soothing-gel", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill TROPIC Sunscreen SPF 50PA ++++ Flex DNA Protection-Shield", slug: "sea-quill-tropic-sunscreen-spf-50pa-flex-dna-protection-shield", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
    { name: "Sea-Quill SPIRULINA Tablet", slug: "sea-quill-spirulina-tablet", image: "/uploads/1774156662396-65c85a0839dab739.jpg", images: ci, shortDescription: cs, description: cd, composition: cc, dosage: cdos, sku: "", tags: ct, stock: true, rating: 5, reviewCount: 0, features: cf, isBestSeller: false, isNew: true, status: "published", sortOrder: 9, categoryId: catMap["mom-kids"] },
  ]});

  console.log("[SEED] Creating blog categories...");
  const blogCategories = await Promise.all([
    prisma.blogCategory.create({ data: { slug: "review", title: "Review", sortOrder: 0 } }),
    prisma.blogCategory.create({ data: { slug: "tips-sehat", title: "Tips Sehat", sortOrder: 1 } }),
    prisma.blogCategory.create({ data: { slug: "imun-daya-tahan-tubuh", title: "Imun & Daya Tahan Tubuh", sortOrder: 2 } }),
    prisma.blogCategory.create({ data: { slug: "nutrisi-gizi", title: "Nutrisi & Gizi", sortOrder: 3 } }),
    prisma.blogCategory.create({ data: { slug: "panduan-suplemen", title: "Panduan Suplemen", sortOrder: 4 } }),
    prisma.blogCategory.create({ data: { slug: "kecantikan", title: "Kecantikan", sortOrder: 5 } }),
  ]);
  const blogCatMap = Object.fromEntries(blogCategories.map((c) => [c.slug, c.id]));

  console.log("[SEED] Creating blog posts...");
  await prisma.blogPost.createMany({ data: [
    { title: "Solusi Tubuh Bugar & Aktif Sepanjang Hari", slug: "keep-loved-ones-healthy", image: "/uploads/1774113218325-df1b1c8db02da9e5.jpg", author: "Jane Doe", content: "<p>Preventive healthcare is the key to long-term well-being. Regular check-ups, screenings, and vaccinations help detect potential health issues early, allowing for timely intervention and reducing the risk of serious illnesses. Simple lifestyle changes such as maintaining a balanced diet, staying active, and managing stress contribute significantly to disease prevention. Investing in preventive care today ensures a healthier future and lowers healthcare costs in the long run.</p>", excerpt: "Preventive healthcare is the key to long-term well-being. Regular check-ups, screenings, and vaccinations help detect potential health issues early.", tags: ["treatment", "health", "clinic", "doctors"], status: "published", categoryId: blogCatMap["tips-sehat"] },
    { title: "7 Cara Mudah Meningkatkan Imunitas Tubuh Setiap Hari", slug: "choose-right-doctor", image: "/uploads/1774113254589-f3e980707d74ba12.jpg", author: "Samantha Green", content: "<p>Preventive healthcare is the key to long-term well-being. Regular check-ups, screenings, and vaccinations help detect potential health issues early, allowing for timely intervention and reducing the risk of serious illnesses. Hypertension, commonly known as high blood pressure, often develops without noticeable symptoms, making it a silent killer. If left untreated, it can lead to serious health complications such as heart disease, stroke, and kidney failure.</p>", excerpt: "Choosing the right primary care doctor is a crucial decision for your health journey. Learn what to look for.", tags: ["treatment", "health", "doctors"], status: "published", categoryId: blogCatMap["panduan-suplemen"] },
    { title: "Pentingnya Omega-3 untuk Kesehatan Jantung dan Otak", slug: "essential-health-screenings", image: "/uploads/1774113504950-2b0c951de44271a2.jpg", author: "Robin Son", content: "<p>Advancements in technology are revolutionizing the healthcare industry, improving patient outcomes and making medical services more accessible. Telemedicine allows patients to consult with doctors remotely, reducing wait times and increasing convenience.</p>", excerpt: "Regular health screenings are vital for early detection. Here are 10 screenings you shouldn't skip.", tags: ["health", "screening"], status: "published", categoryId: blogCatMap["tips-sehat"] },
    { title: "Rahasia Awet Muda: Peran Antioksidan dalam Suplemen", slug: "effective-time-management", image: "/uploads/1774113530188-fcde2bf5ca7bd505.jpg", author: "Jenny Lee", content: "<p>Mental health is closely connected to physical well-being. Stress, anxiety, and depression can contribute to physical ailments such as high blood pressure, digestive issues, and a weakened immune system.</p>", excerpt: "Managing your time effectively can significantly improve your health and productivity.", tags: ["health", "lifestyle"], status: "published", categoryId: blogCatMap["nutrisi-gizi"] },
  ]});

  console.log("[SEED] Creating admin user...");
  await prisma.adminUser.create({ data: { email: "admin@seaquill.com", password: "$2b$12$H5afWJh4xrnpQ8/XIW2IR.xdzFPusKmoLw8akRyfP3C.m5PlrTM.e", name: "Administrator", role: "admin" } });

  console.log("[SEED] Creating site settings...");
  const siteSettings: Record<string, string> = {
    site_name: "Sea-Quill Indonesia",
    site_tagline: "Pilihan Suplemen Tepat untuk Kesehatan Optimal Anda",
    site_description: "Sea-Quill adalah suplemen kesehatan berkualitas dengan berbagai pilihan produk yang telah bersertifikat BPOM dan Halal. Kami berkomitmen membantu masyarakat Indonesia hidup lebih sehat dan aktif setiap hari.",
    site_copyright: "Copyright © 2025 Seaquill. All Rights Reserved.",
    contact_email: "info.seaquill@gmail.com",
    contact_phone: "021-1234-5678",
    contact_address: "Jl. Harmoni Plaza Blok A No. 8, Jakarta Pusat 10150",
    contact_whatsapp: "https://wa.me/6281234567890",
    social_twitter: "https://www.twitter.com/seaquill",
    social_youtube: "https://www.youtube.com/@seaquill",
    social_tiktok: "https://www.tiktok.com/@seaquill",
    social_linkedin: "https://www.linkedin.com/company/seaquill",
    social_pinterest: "",
    social_shopee: "https://shopee.co.id/seaquill",
    social_tokopedia: "https://www.tokopedia.com/seaquill",
    social_lazada: "",
    social_tiktok_shop: "",
    social_facebook: "https://www.facebook.com/seaquill",
    social_instagram: "https://www.instagram.com/seaquill",
    header_logo: "/assets/img/logo.svg",
    header_logo_sticky: "/assets/img/logo.jpg",
    header_badges: `[{"icon":"/assets/img/certified.png","label":"Certified","value":"BPOM Certified"},{"icon":"/assets/img/original.png","label":"Quality","value":"100% Original"},{"icon":"/assets/img/halal.png","label":"Certified","value":"100% Halal"}]`,
    nav_menu: `[{"label":"Beranda","href":"/","submenuSource":""},{"label":"Tentang Seaquill","href":"/tentang","submenuSource":""},{"label":"Produk Seaquill","href":"/produk","submenuSource":"produk"},{"label":"Artikel","href":"/artikel","submenuSource":"artikel"},{"label":"Promo & Event","href":"/promo","submenuSource":""},{"label":"Galeri","href":"/galeri","submenuSource":""},{"label":"Hubungi Kami","href":"/hubungi-kami","submenuSource":""}]`,
    footer_nav: `[{"title":"Produk Seaquill","source":"produk","links":[]},{"title":"Artikel Kesehatan","source":"artikel","links":[]},{"title":"Bantuan & Support","source":"custom","links":[{"label":"FAQs","href":"/faq"},{"label":"Kontak Kami","href":"/hubungi-kami"},{"label":"Kebijakan Privasi","href":"/kebijakan-privasi"},{"label":"Pusat Bantuan","href":"/pusat-bantuan"},{"label":"Syarat & Ketentuan","href":"/syarat-ketentuan"}]}]`,
    home_feature_cards: `[{"title":"Tips & Edukasi Kesehatan","text":"Temukan artikel, tips kesehatan, dan informasi gaya hidup sehat untuk mendukung aktivitas dan keseharian Anda bersama Sea-Quill","btnText":"Baca Artikel","href":"/artikel"},{"title":"Terstandar BPOM & Halal","text":"Seluruh produk Sea-Quill telah bersertifikat BPOM dan Halal, diproduksi dengan standar internasional dan keamanan maksimal.","btnText":"Tentang Seaquill","href":"/tentang"},{"title":"100% Original & Promo Menarik","text":"Nikmati produk original langsung dari distributor resmi dengan promo spesial setiap bulan. Belanja aman dan nyaman di sini.","btnText":"Lihat Promo","href":"/hubungi-kami"}]`,
    home_about_section: `{"subTitle":"Tentang Seaquill!","heading":"Pilihan Tepat, untuk Hidup Sehat dan Berkualitas!!","paragraph":"Sea-Quill menghadirkan suplemen kesehatan terpercaya, dibuat dengan standar internasional dan inovasi terkini. Kami berkomitmen mendukung Anda dan keluarga dalam menjaga daya tahan tubuh dan kualitas hidup setiap hari!","checklist":["Telah lulus uji BPOM dan bersertifikat Halal.","Direkomendasikan oleh para ahli nutrisi.","Formula sesuai kebutuhan masyarakat Indonesia.","Mendukung gaya hidup sehat dan aktif.","Pilihan lengkap untuk berbagai kebutuhan nutrisi!"],"ctaText":"Selengkapnya tentang Sea-Quill!","ctaLink":"/tentang","image1":"/assets/img/home/home-3.jpg","image2":"/assets/img/home/home-1.jpg","image3":"/assets/img/home/home-2.jpg"}`,
    home_service_list: `{"subTitle":"Pilihan Produk!","heading":"Manfaat Utama Produk Sea-Quill!","paragraph":"Dapatkan manfaat optimal dari produk-produk Sea-Quill, diproses dengan teknologi terbaik dan selalu mengutamakan kualitas, keamanan, dan edukasi untuk keluarga Indonesia!","items":[{"icon":"/assets/img/icon/service_1_1.svg","title":"Imunitas & Daya Tahan Tubuh!","text":"Bantu tingkatkan sistem kekebalan tubuh Anda agar tetap fit dan tidak mudah sakit, cocok untuk segala usia!","image":"/assets/img/home/home-4.jpg","buttonText":"Selengkapnya!"},{"icon":"/assets/img/icon/service_1_2.svg","title":"Kesehatan Jantung & Pembuluh Darah","text":"Jaga kesehatan jantung, kolesterol, dan tekanan darah Anda dengan suplemen yang diformulasikan khusus.","image":"/assets/img/home/home-5.jpg","buttonText":"Selengkapnya!"},{"icon":"/assets/img/icon/service_1_3.svg","title":"Nutrisi Anak & Keluarga","text":"Dukungan nutrisi lengkap untuk tumbuh kembang anak dan kesehatan seluruh keluarga.","image":"/assets/img/home/home-6.jpg","buttonText":"Selengkapnya!"},{"icon":"/assets/img/icon/service_1_4.svg","title":"Vitalitas & Energi","text":"Bantu tingkatkan stamina, energi, dan vitalitas tubuh untuk aktivitas sehari-hari yang optimal.","image":"/assets/img/home/home-7.jpg","buttonText":"Selengkapnya!"}]}`,
    home_product_section: `{"subTitle":"Sea-Quill!","heading":"Produk Unggulan!","paragraph":"Temukan suplemen terbaik Sea-Quill untuk mendukung kesehatan keluarga Anda. Setiap produk terjamin keaslian, kualitas, dan sudah BPOM serta Halal.!"}`,
    home_blog_section: `{"subTitle":"Artikel Kesehatan!","heading":"Blog & Berita Sea-Quill!","paragraph":"Temukan update seputar produk, edukasi, dan tren kesehatan terbaru langsung dari Sea-Quill.!"}`,
    home_featured_flags: `{"bestSeller":true,"newProduct":false}`,
    tentang_about_section: `{"subTitle":"Tentang Seaquill!","headingNormal":"Pilihan Tepat!","heading":"untuk Hidup Sehat dan Berkualitas!","paragraph":"Sea-Quill menghadirkan suplemen kesehatan terpercaya, dibuat dengan standar internasional dan inovasi terkini. Kami berkomitmen mendukung Anda dan keluarga dalam menjaga daya tahan tubuh dan kualitas hidup setiap hari!","checklist":["Formulasi berbahan baku alami & premium!","Aman, sudah bersertifikat BPOM & Halal MUI","Membantu menjaga daya tahan tubuh setiap hari","Mendukung kesehatan jantung, otak, dan sendi","Pilihan suplemen lengkap sesuai kebutuhan Anda"],"aboutImage":"/uploads/1774204344704-4ace174d8f8aa877.jpg","videoImage":"/uploads/1774204893613-fa56e43f61812769.mp4","videoUrl":""}`,
    tentang_feature_cards: `[{"title":"Pilihan Suplemen Lengkap!","text":"Dari kesehatan jantung, daya tahan tubuh, hingga kecantikan kulit \u2013 Sea-Quill hadir untuk seluruh kebutuhan keluarga.!","btnText":"Lihat Produk!","href":"/produk"},{"title":"Terbukti Aman & Berkualitas","text":"Seluruh produk Sea-Quill telah lolos uji BPOM dan bersertifikat Halal, serta diproduksi sesuai standar internasional.","btnText":"Tentang Kami","href":"/tentang"},{"title":"Dukungan Konsultasi","text":"Konsultasikan kebutuhan suplemen Anda dengan tim kami. Kami siap membantu memilih produk yang paling sesuai.","btnText":"Konsultasi","href":"/hubungi-kami"}]`,
    tentang_project_slider: `{"subTitle":"Tentang Sea-Quill!","headingNormal":"Solusi Suplemen Modern,!","heading":"Kesehatan Berkualitas Setiap Hari!","paragraph":"Sea-Quill adalah merek suplemen kesehatan terkemuka yang telah dipercaya masyarakat Indonesia untuk mendukung gaya hidup sehat. Dengan formulasi berkualitas tinggi, bahan alami, dan sertifikasi BPOM serta Halal, Sea-Quill selalu berkomitmen menghadirkan inovasi dan manfaat nyata bagi setiap keluarga Indonesia.!","sideParagraph":"We have world class lab assistants. We are equipped with best medical services & reagents. We ensure best quality findings.!","items":[{"img":"/uploads/1774113530188-fcde2bf5ca7bd505.jpg","title":"Produk Original 100% (BPOM & Halal)!","text":"Setiap produk Sea-Quill terjamin keasliannya, memiliki sertifikasi BPOM dan Halal MUI. Aman untuk dikonsumsi setiap hari.!"},{"img":"/uploads/1774113504950-2b0c951de44271a2.jpg","title":"Varian Produk Lengkap","text":"Tersedia lebih dari 30 varian produk: multivitamin, Omega-3, herbal, kalsium, dan lain-lain, sesuai kebutuhan kesehatan Anda."},{"img":"/uploads/1774113254589-f3e980707d74ba12.jpg","title":"Manfaat Terbukti & Inovasi Terkini","text":"Didukung riset ilmiah, Sea-Quill terus menghadirkan inovasi formula untuk hasil optimal bagi kesehatan keluarga Anda."}],"loop":true,"autoplay":true}`,
    hubungi_social_section: `{"heading":"Temukan dan Ikuti Sea-Quill","subTitle":"Platform Sosial Media Kami","items":[{"platform":"Instagram","icon":"/assets/img/icon/instagram.svg","title":"@seaquill.id","description":"Dapatkan info promo, edukasi kesehatan, dan inspirasi gaya hidup sehat langsung dari Instagram resmi Sea-Quill.","link":"https://instagram.com/seaquill.id","btnText":"Kunjungi Instagram"},{"platform":"Facebook","icon":"/assets/img/icon/facebook.svg","title":"Sea-Quill Indonesia","description":"Like dan follow Facebook Sea-Quill untuk update berita, tips kesehatan, dan testimoni pengguna.","link":"https://facebook.com/seaquill.indonesia","btnText":"Kunjungi Facebook"},{"platform":"TikTok","icon":"/assets/img/icon/tiktok.svg","title":"@seaquill.id","description":"Saksikan konten seru, tips kesehatan, dan edukasi suplemen dengan format video di TikTok Sea-Quill.","link":"https://tiktok.com/@seaquill.id","btnText":"Kunjungi TikTok"}]}`,
    hubungi_marketplace_section: `{"heading":"Belanja Produk Sea-Quill di Sini","subTitle":"Marketplace Resmi Sea-Quill","items":[{"platform":"Tokopedia","icon":"/assets/img/icon/tokopedia.svg","title":"Tokopedia Official","description":"Dapatkan produk Sea-Quill original dan promo menarik langsung dari official store kami di Tokopedia.","link":"https://tokopedia.com/seaquill","btnText":"Beli di Tokopedia"},{"platform":"Shopee","icon":"/assets/img/icon/shopee.svg","title":"Shopee Official","description":"Cari produk Sea-Quill dan nikmati kemudahan belanja serta voucher di Shopee.","link":"https://shopee.co.id/seaquill","btnText":"Beli di Shopee"},{"platform":"Lazada","icon":"/assets/img/icon/lazada.svg","title":"Lazada Official Store","description":"Nikmati pengalaman belanja produk Sea-Quill yang aman dan mudah, dengan promo eksklusif dan layanan pengiriman cepat hanya di Lazada Official Store kami.","link":"https://www.lazada.co.id/shop/seaquill-official/","btnText":"Beli di Lazada"},{"platform":"TikTok Shop","icon":"/assets/img/icon/tiktok.svg","title":"TikTok Shop Official","description":"Belanja langsung lewat TikTok Shop Sea-Quill dan dapatkan penawaran spesial serta flash sale selama live streaming bersama kami!","link":"https://www.tiktok.com/@seaquill.id/shop","btnText":"Beli di TikTok Shop"}]}`,
    hubungi_contact_section: `{"heading":"Kirim Pesan kepada Kami","subTitle":"Hubungi Kami"}`,
    hero_slider_config: `{"autoplay":true,"autoplayDelay":3000,"loop":true,"pauseOnHover":false}`,
    product_slider_config: `{"autoplay":true,"autoplayDelay":3000,"loop":true,"pauseOnHover":false}`,
    brand_slider_config: `{"autoplay":true,"autoplayDelay":3000,"loop":true,"pauseOnHover":false}`,
    blog_slider_config: `{"autoplay":true,"autoplayDelay":3000,"loop":true,"pauseOnHover":false}`,
  };
  await Promise.all(Object.entries(siteSettings).map(([key, value]) => prisma.siteSetting.create({ data: { key, value } })));

  console.log("[SEED] Creating hero slide group and slides...");
  const heroSlideGroup = await prisma.heroSlideGroup.create({ data: { name: "Promo 1", description: "Untuk Promo 1", active: true } });
  await prisma.heroSlide.createMany({ data: [
    { subtitle: "Sehat Setiap Hari, Nikmati Hidup Berkualitas!", title: "Sea-Quill, Suplemen Terpercaya Untuk Kesehatan Anda dan Keluarga!", bgImage: "/assets/img/hero/hero_bg_1_1.jpg", ctaText: "Jelajahi Produk!", ctaLink: "/produk", ctaText2: "Cek Manfaat Suplemen!", ctaLink2: "/artikel", sortOrder: 1, active: true, groupId: heroSlideGroup.id },
    { subtitle: "Imun Kuat, Aktivitas Tanpa Batas", title: "Dukung Daya Tahan Tubuh Dengan Sea-Quill Solusi Suplemen Pilihan.", bgImage: "/assets/img/hero/hero_bg_1_1.jpg", ctaText: "Jelajahi Produk", ctaLink: "/produk", ctaText2: "Cek Manfaat Suplemen", ctaLink2: "/artikel", sortOrder: 2, active: true, groupId: heroSlideGroup.id },
    { subtitle: "Pilihan Suplemen Terbaik Untuk Anda", title: "Raih Hidup Sehat, Aktif, dan Bugar Bersama Sea-Quill, Setiap Hari.", bgImage: "/assets/img/hero/hero_bg_1_1.jpg", ctaText: "Jelajahi Produk", ctaLink: "/produk", ctaText2: "Cek Manfaat Suplemen", ctaLink2: "/artikel", sortOrder: 3, active: true, groupId: heroSlideGroup.id },
  ]});

  console.log("[SEED] Creating brand partners...");
  await prisma.brandPartner.createMany({ data: [
    { name: "Kimia Farma", logoImage: "/assets/img/home/kimia-farma.png", url: "", sortOrder: 1, active: true },
    { name: "Watsons", logoImage: "/assets/img/home/watson.png", url: "", sortOrder: 2, active: true },
    { name: "Guardian", logoImage: "/assets/img/home/guardian.png", url: "", sortOrder: 3, active: true },
    { name: "Wellings", logoImage: "/assets/img/home/wellings.png", url: "", sortOrder: 4, active: true },
    { name: "Boston", logoImage: "/assets/img/home/boston.png", url: "", sortOrder: 5, active: true },
    { name: "Century", logoImage: "/assets/img/home/century.png", url: "", sortOrder: 6, active: true },
    { name: "Boots", logoImage: "/assets/img/home/boots.png", url: "", sortOrder: 7, active: true },
  ]});

  console.log("[SEED] Creating gallery items...");
  await prisma.galleryItem.createMany({ data: [
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Seaquill Products", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 1, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Healthy Living", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 2, active: true },
    { image: "/assets/img/widget/gallery_1_3.jpg", caption: "Wellness Tips", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 3, active: true },
    { image: "/assets/img/widget/gallery_1_4.jpg", caption: "Supplement Guide", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 4, active: true },
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Product Showcase", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 5, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Health Education", platform: "instagram", url: "https://www.instagram.com/p/C6yIzzALxZe/", sortOrder: 6, active: true },
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Seaquill Community", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 1, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Health Tips", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 2, active: true },
    { image: "/assets/img/widget/gallery_1_3.jpg", caption: "Product Info", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 3, active: true },
    { image: "/assets/img/widget/gallery_1_4.jpg", caption: "Wellness Journey", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 4, active: true },
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Daily Health", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 5, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Supplement Facts", platform: "facebook", url: "https://facebook.com/seaquill.indonesia", sortOrder: 6, active: true },
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Seaquill TikTok", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 1, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Health Reels", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 2, active: true },
    { image: "/assets/img/widget/gallery_1_3.jpg", caption: "Supplement Tips", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 3, active: true },
    { image: "/assets/img/widget/gallery_1_4.jpg", caption: "Healthy Lifestyle", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 4, active: true },
    { image: "/assets/img/widget/gallery_1_1.jpg", caption: "Wellness Content", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 5, active: true },
    { image: "/assets/img/widget/gallery_1_2.jpg", caption: "Product Review", platform: "tiktok", url: "https://tiktok.com/@seaquill.id", sortOrder: 6, active: true },
  ]});

  console.log("[SEED] Creating promo items...");
  await prisma.promoItem.createMany({ data: [
    { title: "Flash Sale 8.8 Seaquill", description: "Diskon hingga 40% untuk produk pilihan! Promo hanya berlaku 8-10 Agustus 2025. Jangan lewatkan!", image: "/assets/img/gallery/gallery_1_1.jpg", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 1, active: true },
    { title: "Cashback Spesial Shopee", description: "Belanja Seaquill di Shopee dapatkan cashback hingga Rp 50.000 tanpa minimum belanja.", image: "/assets/img/gallery/gallery_1_3.jpg", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 2, active: true },
    { title: "Gratis Ongkir Tokopedia", description: "Dapatkan gratis ongkir untuk pembelian semua produk Seaquill di Tokopedia selama bulan ini!", image: "/assets/img/gallery/gallery_1_4.jpg", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 3, active: true },
    { title: "Beli 2 Gratis 1 Multivitamin", description: "Setiap pembelian 2 botol multivitamin Seaquill, dapatkan 1 botol gratis. Berlaku hanya untuk produk tertentu selama Agustus 2025.", image: "/assets/img/gallery/gallery_1_5.jpg", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 4, active: true },
    { title: "Bundling Hemat Seaquill", description: "Dapatkan paket bundling Seaquill dengan harga spesial! Kombinasi produk pilihan untuk kebutuhan kesehatan keluarga Anda.", image: "/assets/img/gallery/gallery_1_2.jpg", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 5, active: true },
  ]});

  console.log("[SEED] Creating event items...");
  await prisma.eventItem.createMany({ data: [
    { title: `Live Streaming: "Rahasia Imun Kuat Bersama Nutritionist"`, description: "Jangan lewatkan sesi live edukasi bareng pakar nutrisi Seaquill. Ada hadiah voucher untuk penanya terbaik!", image: "/assets/img/blog/blog_4_1.jpg", date: "21 Agustus 2025", location: "Instagram Live", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 1, active: true },
    { title: `Seaquill Tokopedia Play: "Quiz & Hadiah"`, description: "Main quiz live di Tokopedia Play, menangkan produk Seaquill gratis untuk 5 peserta tercepat!", image: "/assets/img/blog/blog_4_2.jpg", date: "31 Agustus 2025", location: "Tokopedia Play", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 2, active: true },
    { title: "Fun Walk & Health Check Gratis", description: "Ikuti Fun Walk Seaquill di Jakarta dan dapatkan pemeriksaan kesehatan gratis serta goody bag menarik!", image: "/assets/img/blog/blog_4_3.jpg", date: "10 September 2025", location: "Offline Jakarta", ctaText: "Lihat Detail", ctaLink: "#", sortOrder: 3, active: true },
  ]});

  console.log("[SEED] Done! All tables seeded successfully.");
  console.log("   Product categories: 8, Products: 38, Blog categories: 6, Blog posts: 4");
  console.log("   Site settings: " + Object.keys(siteSettings).length + ", Hero slides: 3");
  console.log("   Brand partners: 7, Gallery items: 18, Promo items: 5, Event items: 3");
}

seedAllTables()
  .catch((e) => {
    console.error("[SEED] Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });